Repository genn-team/ml_genn, pull requests merged in 2025-02, with the labels that each got.

#131 Numerous typos in loading delays
  ml_genn/ml_genn/compilers/compiler.py
Labels: bug

#132 docs: Add comprehensive Inference compiler documentation
  docs/index.rst
  docs/usage/inference.rst
Labels: documentation

#134 Postsynaptic model optimisation
  ml_genn/ml_genn/utils/auto_model.py
Labels: enhancement
